### ISSUE TITLE
The web link does not work

### ISSUE THREAD

**Issue by randel** [OSU-BMBL/scread#19]
Hi, the link does not work for me. https://bmbls.bmi.osumc.edu/scread/ Not sure if this is an issue for all.

**Comment by kunhyungroh** [comment]
Same issue here...any updates?

**Comment by vmalysheva** [comment]
Same issue here... :(

**Comment by Wang-Cankun** [comment]
scREAD has been migrated to http://osubmi.com/scread. Thanks for your support!
