### ISSUE TITLE
Notebook fails to run 

### ISSUE THREAD

**Issue by mzachariou** [OSU-BMBL/scread#28]
Hi there, I tried to run the  google colab notebook (used to work in the past) but now it fails to load the scREAD data and gives  the following error:

Warning message in load(url("https://github.com/OSU-BMBL/scread-protocol/raw/master/overlapping_genes/scread_db.rdata")):
“input string '10<96>12 months' cannot be translated to UTF-8, is it valid in 'CP936'?”
Error in value[[3L]](cond): attempt to apply non-function

Can you please advice on how to proceed?

**Comment by Wang-Cankun** [comment]
The main server is in maintenance so the link does not for now. I have updated the database URL, now it will only load from GitHub. 
Note that the finding overlapping DEG function is also available on scREAD website now: http://osubmi.com/scread/
