### ISSUE TITLE
Download data is duplicate

### ISSUE THREAD

**Issue by Tim0thy1** [OSU-BMBL/scread#32]
Hi, thanks for your great jobs first.

I downloaded the dataset data from [(https://bmblx.bmi.osumc.edu/ssread/downloads )]
I found there are some data is duplicate  which md5 are same

```
f8a6e0a4fe6df5463da585797c7148fc  AD00102_expr.txt.gz
f8a6e0a4fe6df5463da585797c7148fc  AD01102_expr.txt.gz
f8a6e0a4fe6df5463da585797c7148fc  AD01302_expr.txt.gz
f8a6e0a4fe6df5463da585797c7148fc  AD01906_expr.txt.gz
```

What is reason for this? 
sorry, my english is not good.

**Comment by Wang-Cankun** [comment]
Hi, thanks for using the database. I am still developing the ssREAD. Please download the datasets from the published version https://osubmi.com/scread/
